### ISSUE TITLE
Line 310 wifi connection issue

### ISSUE THREAD

**Issue by marcolumia** [Phoenix260/Drop-BOB#4]
Hey you'll need to set these as variables
# L310

```
Blynk.begin(auth, "ASUS-BOB-BOB-Jelly-Jube", "fuck off get your own");
```

ref: https://github.com/Phoenix260/Drop-BOB/blob/master/Drop-BOB.ino#L310

**Comment by marcolumia** [comment]
I was going to make the change, but I would edit the entire file due to spacing CRLF

**Comment by Phoenix260** [comment]
Ya, Tommy noticed it too. What's spacing CRLF?

I'm still scratching my head on how to have people input that without having to modify code...

I think the key is using the access point feature on the ESP8266... I still have to read more.

**Comment by marcolumia** [comment]
Windows uses CRLF, Mac uses CR and linux uses LF. Anytime a mac updates a file by windows, it replaces the entire file instead of the line changed. Basically just needs to set it so all machines work on the LF line ending as it’s the general method by almost all code.

It’s not a big deal, there’s a git config to be set to ignore line endings and I think you can setup the repo to force a line ending style.

As for setting the wifi connections outside of the code, im wondering if a connection with a phone for setup might work. I honestly have no idea what options there are. I looked a little into using a mobile phone as a setup UI but didn’t get far with that.

Regards,
Marco
